### ISSUE TITLE
[M] Front-end updates for Protected Areas

### ISSUE THREAD

**Issue by Dianadec** [bcgov/parks-data-register#412]
Upon going through the flow for Sites edits, we have decided to update how editing works. Since Protected Areas use the same workflow, we will need to update the UI for them as well.

## Acceptance Criteria
Given that I am a BC Parks admin user
When I click the edit button on a Protected Area record view page
then a dropdown appears with 3 edit options: `Make a minor edit`, `Change legal name`, `Set status to repealed`

Given that I am a BC Parks admin user
When I see the Protected Area search table
then the only icon I see is the View icon, which will take me to the View record page

## Clickable prototype
https://www.figma.com/proto/qdjegD6YHWZPlyFT8dGXvk/Data-Register?type=design&node-id=4361-116757&t=KRBDpucZHEPKgzYq-0&scaling=min-zoom&page-id=4361%3A116641&starting-point-node-id=4361%3A116757

## Notes
- this involves removing the pencil edit icon in the table

**Comment by manuji** [comment]
Tested on TEST: Failed

* Missing the eye icon on the Search table. 
* When clicked on the Cancel button from Minor edit, Major edit or Repeal screens, user get navigated to a random broken page. 
* When repealing a park, an incorrect error is displayed saying: " No repeals permitted on a repealed protected area. "


![Image](https://github.com/bcgov/parks-data-register/assets/65190263/5ff42f23-97d6-449a-8850-51622f0f414b)


https://github.com/bcgov/parks-data-register/assets/65190263/9c6b6ffb-d65d-41b2-bcef-034fcd823c37

**Comment by manuji** [comment]
**QA Note:** It was decided by the team to remove the view icon from the Search results table.

**Comment by cameronpettit** [comment]
Fixed the two remaining issues in #422

**Comment by manuji** [comment]
@cameronpettit , i am still seeing the issue when i click Cancel from the Repeal screen.

**Comment by manuji** [comment]
Tested on TEST: Pending
* When I repeal a park name, the resulting page shows empty field and does not return to the values of the Park details on the View screen. 


https://github.com/bcgov/parks-data-register/assets/65190263/c9af3706-bd60-4d57-8408-bc0e4e6289db

**Comment by cameronpettit** [comment]
Fixed in #427

**Comment by manuji** [comment]
Tested on TEST: **Passed**
*Verified that this issue has been fixed. 
* Passing to PO review.

**Comment by JLWade** [comment]
working as expected - moving to done
